### ISSUE TITLE
HTTP error 400 since October 4th

### ISSUE THREAD

**Issue by x-ian** [DrHauss/node-red-contrib_BRP069C4#15]
Since Oct 4 2022 my Node-RED flows show the error "HTTPError: Response code 400 (Bad Request)" when accessing the Daikin cloud (via username/password).

Recently I noticed that the iOS app also required a (mandatory?) update. Are there known changes in the cloud communication that prevent node-red-contrib-daikin-cloud to work as of now?

**Comment by DrHauss** [comment]
Sorry, on my site I have no issues. Did you enable Save Token? If yes please disable and delete tokenset.json. Please also enable debugging and provide logs to have a look why it is not working for you.

**Comment by x-ian** [comment]
This already was helpful. Working again for me.

Save Token was not enabled; the logs didn't reveal anything else. But I did a clean install in NodeRED via npm and rebooted the system. Now back to working; most likely not related to your package. Closing the issue.

Sorry for the false report. And many thanks for the quick feedback!!!
