### ISSUE TITLE
HTTPError: Response code 400 (Bad Request) every few weeks

### ISSUE THREAD

**Issue by EriHau** [DrHauss/node-red-contrib_BRP069C4#19]
I query the status of the devices 1x per minute. Every few weeks the cloud query stops working for me. Then an "HTTPError: Response code 400 (Bad Request)" comes up every minute. A complete restart of the Node Red  fixes the error again for a few weeks. The bad thing is that the error is displayed in the status of the node, but is not detected by the catch-node. So it is not possible for me to report the error to my HMI. I only notice it when I randomly enter the node-red (or when switching commands are not executed and it gets cold in heating mode). Save Token is disabled.

**Comment by DIY-Blub** [comment]
I have exactly the same problem.

- "HTTPError: Response code 400 (Bad Request)"
- A complete restart of the Node Red fixes the error again for a few weeks. 
- catch-node doesn't get a debug message
- no Token

**Comment by vigeland** [comment]
The same problem

**Comment by mgugu10** [comment]
Same problem for me

**Comment by DrHauss** [comment]
@DIY-Blub The issue that this is not handled with the catch node occurs because the used node.error in the source need to be adopted to send back the msg.

**Comment by DrHauss** [comment]
I have the same issue btw. This happens because of the used library https://github.com/Apollon77/daikin-controller-cloud/ is not handling the situation when the token is no longer valid correct. The only way is to restart the flow to fix this issue for some weeks.

**Comment by EriHau** [comment]
Apollon77 published several new versions of the used library https://github.com/Apollon77/daikin-controller-cloud/ within the last few days. Is there a possibility that the latest version helps to solve our problem?

**Comment by DrHauss** [comment]
This pull request might be the solution for our issue

[Pull request](https://github.com/Apollon77/daikin-controller-cloud/pull/116)

I will try to update our node-red library to be compatible with this version of daikin-controller-cloud
