### ISSUE TITLE
Can't set temperature for heating less than 18°

### ISSUE THREAD

**Issue by EriHau** [DrHauss/node-red-contrib_BRP069C4#24]
I have several rooms, where I want to heat in winter only up to a temperature of 15. And also in one room I have to set the temperature for heating with an offset of -3. So if I want 20 I have to st it to 17 because of the geometry of the room. But setting a temperature less than 18 from node-red results in an error 

`Error: Value (15) must not be smaller then 18`

As far as I understand the code, all three temperatures (heating, cooling and auto) are set regardless which mode is active. When I look at the possible ranges I see that for heating **10**..31, for cooling 18..33 and for auto 18..30 is possible. 

`{"/operationModes/heating/setpoints/roomTemperature":{"settable":true,"value":15,"unit":"°C","stepValue":0.5,"minValue":10,"maxValue":31},"/operationModes/cooling/setpoints/roomTemperature":{"settable":true,"value":30,"unit":"°C","stepValue":0.5,"minValue":18,"maxValue":33},"/operationModes/auto/setpoints/roomTemperature":{"settable":true,"value":30,"unit":"°C","stepValue":0.5,"minValue":18,"maxValue":30}}`

So setting in heating mode to a temperature of 15 results in an error because Daikin does not allow a cooling and auto of less than 18. In my opinion the temperatureControl should only be set to the active mode of the unit to allow heating also in a range from 10 to 18 degree.

**Comment by DrHauss** [comment]
Hi @EriHau could you please test the latest release 0.4.0. There is now a config switch in the node config where you could disable the temperature sync feature.

**Comment by DrHauss** [comment]
Afterwards please make sure to set msg.payload.dataPointPath to "/operationModes/heating/setpoints/roomTemperature" or others when you want to switch the temperature. It is no longer possible then to switch temperature without dataPointPath set. If you want to set it for all three you need to make this for all 3 modes seperately.

**Comment by EriHau** [comment]
It works perfect! Thank you for the quick and easy solution.
