### ISSUE TITLE
Unable to Login to the cloud.

### ISSUE THREAD

**Issue by MikeEcho0815** [DrHauss/node-red-contrib_BRP069C4#25]
The adapter is no longer able to login to the account (while the App still does). 
![image](https://github.com/DrHauss/node-red-contrib_BRP069C4/assets/45940028/7a3726a2-d204-458b-a0e1-c09a14db0f7e)

**Comment by DrHauss** [comment]
Sorry but I cannot support you without additional information. Which request did you sent to Daikin. When does this error occur. What is the output of the log?

**Comment by MikeEcho0815** [comment]
Of course. Thank you for your fast reply.

i am sending:
![image](https://github.com/DrHauss/node-red-contrib_BRP069C4/assets/45940028/51f25e6c-4b11-4a0a-9fee-12eb358eef90)


node-config:
![image](https://github.com/DrHauss/node-red-contrib_BRP069C4/assets/45940028/f97bde5d-ca7a-4efb-ae29-45951f88a7e1)

output on debug node:
![image](https://github.com/DrHauss/node-red-contrib_BRP069C4/assets/45940028/7882e962-0bbf-43d6-bbe8-a94196154e27)


If there is information missing, please let me know.

**Comment by DrHauss** [comment]
Sorry but this is not enough. You need the http response from the API request. 

![image](https://github.com/DrHauss/node-red-contrib_BRP069C4/assets/10944060/2b8c034d-123d-473c-8df2-359201e11134)

Please change to debug on the file and check your Node log

**Comment by MikeEcho0815** [comment]
I changed the file to "debug", but the node output doesn't change.
Are we talking about the debug node output?

**Comment by DrHauss** [comment]
No you have to check the console output

**Comment by MikeEcho0815** [comment]
Could you give me a hint, how to do that? That would be nice.

**Comment by mgugu10** [comment]
I experienced the same problem and I got a temporary workaround (before Daikin breaking changes) at https://github.com/Apollon77/daikin-controller-cloud/issues/128#issuecomment-1986872478](url)](https://github.com/Apollon77/daikin-controller-cloud/issues/128#issuecomment-1986872478)
It consists of disconnecting from Onecta and connecting again by filling the new registrations fields.
Same question as @MikeEcho0815 : How to simply get (or filter) the daikin node logs at docker console ?

**Comment by DrHauss** [comment]
Logging topic will be handled with #26

**Comment by MikeEcho0815** [comment]
So ,is there any new development?

Should the adapter work right now?

**Comment by DrHauss** [comment]
@MikeEcho0815 for me it is still working. The main implementation needs to be done in the daikon-controller-cloud module. As Long there is bi change in the module nothing could be done on our site
