### ISSUE TITLE
ErrorCode 400 on login via NodeRed

### ISSUE THREAD

**Issue by marcodanese** [DrHauss/node-red-contrib_BRP069C4#27]
Since few days, receive error 400 (bad request)  on every request (GET/SET).
Is an error only on my nodered server?

**Comment by marcodanese** [comment]
![Screenshot from 2024-06-07 09-40-13](https://github.com/DrHauss/node-red-contrib_BRP069C4/assets/29493289/277879b3-9d57-4be6-a099-831eae37e1a6)

for sure the server is online, with internet access

**Comment by marcodanese** [comment]
![Screenshot from 2024-06-14 09-07-59](https://github.com/DrHauss/node-red-contrib_BRP069C4/assets/29493289/5d671781-f70b-44c6-9880-cf6b3816f37c)

no other message from the log

**Comment by DrHauss** [comment]
Try to re-login to your daikin app on your mobile and check if there is  something you need to be agree.
