### ISSUE TITLE
Node-red flow example

### ISSUE THREAD

**Issue by andispammonyer** [DrHauss/node-red-contrib_BRP069C4#7]
Hi,

would it be possible for you to export your existing node-red flow? Or explain what I need to feed into your node. The existing explanation "msg.payload.ssid = Device SSID" and so on, does not work for me.
I use your Daikin cloud controller node with node red 6.0.4.
I'm able to GET the status of my three daikin devices with BRP069C4.

But I'm NOT able to SET something. 
Main Use Case would be

- On/Off
- Heating/Cooling
- Power Mode On/Off
- Target Temp

I run Node red as addon of my Raspberrymatic called redmatic. Just in case this matters. I want to controll the AC from homematic

Thanks in advance!

**Comment by DrHauss** [comment]
Hi @andispammonyer this is how it look like for on off:

`[{"id":"6df8ed305ff1d464","type":"inject","z":"261ed1a6cb4d6379","name":"","props":[{"p":"topic","vt":"str"},{"p":"payload"},{"p":"payload.ssid","v":"DaikinAP86971","vt":"str"},{"p":"payload.managementPoint","v":"climateControl","vt":"str"},{"p":"payload.dataPoint","v":"onOffMode","vt":"str"},{"p":"payload.value","v":"off","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"set","payload":"{}","payloadType":"json","x":170,"y":460,"wires":[["062808176aba3b76","bad8598fbd2a57cb"]]},{"id":"062808176aba3b76","type":"Daikin-Cloud-Controller","z":"261ed1a6cb4d6379","name":"","loglevel":"warn","tokensave":"0","timeout":"10000","retry":"3","x":470,"y":300,"wires":[["9ad9b4f3625ab0c0"]]},{"id":"bad8598fbd2a57cb","type":"debug","z":"261ed1a6cb4d6379","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":460,"y":240,"wires":[]},{"id":"9ad9b4f3625ab0c0","type":"debug","z":"261ed1a6cb4d6379","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload","statusType":"auto","x":710,"y":200,"wires":[]}]`

**Comment by andispammonyer** [comment]
It works!!! Perfect. Many thanks
The second line with payload `{}` was missing on my side
